/*<View style={{width:'100%',display:'flex',flexDirection:'row',justifyContent:'space-between'}}>
            <Tile
                height={200}
                width={windowWidth/2}
                imageSrc={require('./images/shifaaz-shamoon-oR0uERTVyD0-unsplash.jpg')}
                featured
                title="Save the Planet!"
                titleStyle={{fontSize:15}}
                onPress={()=>{navigation.navigate('Help Others')}}
            />
            <Tile
                height={200}
                width={windowWidth/2}
                imageSrc={require('./images/adityan-ramkumar-koIXNKW8Sc4-unsplash.jpg')}
                featured
                title="Help others!"
                titleStyle={{fontSize:15}}
                onPress={()=>{navigation.navigate('Help Others')}}
            />
        </View>


        <Card width={'97%'} containerStyle={{position:'relative',display:'flex',alignSelf:'center',backgroundColor:'#0C0C0C',borderRadius:10}}>
        <Card.Title style={{color:'white'}}>Are you lost? Notify our search teams!</Card.Title>
        <Card.Divider/>
        <Card.Image source={require('./images/warren-wong-fNUNt9w3m-Q-unsplash.jpg')}>
        </Card.Image>
        </Card>

        */